nome = "Alessandro"
cognome = "Pachera"
età = 18
corso = "Tec info"
altezza = 1.81
presenza = True

print(f"Mi presento: \nMi chiamo {nome} {cognome} e ho {età} anni.")
print(f"Studio nel corso di {corso}.")
print(f"Altezza {altezza} m.")

if presenza:
    print("Oggi sono presente.")
else:
    print("Oggi sono assente.")

print ("======IL MIO AMICO ======")

nomeAmica = "Tina"
cognomeAmica = "Ponte"
etàAmica = 42
corsoAmica = "Tec info"
altezzaAmica = 1.72
presenzaAmica = True

print(f"Ciao, la mia amica è {nomeAmica} {cognomeAmica}. Lei è la responsabile del corso {corsoAmica} e ha {etàAmica} anni.")

if presenzaAmica:
    print(f"Anche {nomeAmica} è presente.")
else:
    print(f"Oggi {nomeAmica} non è presente.")
